version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
  assignees:
    - "ezio-melotti"
  open-pull-requests-limit: 10

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
  assignees:
    - "ezio-melotti"
  open-pull-requests-limit: 10
